// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/stock-daily-data": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票日线数据"
                ],
                "summary": "获取全部股票日线数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StockDailyData"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票日线数据"
                ],
                "summary": "新增股票日线数据",
                "parameters": [
                    {
                        "description": "股票日线数据",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StockDailyData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.StockDailyData"
                        }
                    }
                }
            }
        },
        "/stock-daily-data/{symbol}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票日线数据"
                ],
                "summary": "根据股票代码和交易日期查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "股票代码",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "交易日期(YYYY-MM-DD)",
                        "name": "trade_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StockDailyData"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票日线数据"
                ],
                "summary": "删除@Tags 股票日线数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "股票代码",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "交易日期(YYYY-MM-DD)",
                        "name": "trade_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deleted",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stocks": {
            "get": {
                "description": "获取所有股票的基础信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票信息"
                ],
                "summary": "获取所有股票信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StockBasicInfo"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "新增一条股票基础信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票信息"
                ],
                "summary": "创建股票信息",
                "parameters": [
                    {
                        "description": "股票信息",
                        "name": "stock",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StockBasicInfo"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.StockBasicInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stocks/symbol/{symbol}": {
            "get": {
                "description": "通过股票代码获取股票基础信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票信息"
                ],
                "summary": "根据股票代码获取股票信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "股票代码",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StockBasicInfo"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "通过股票代码删除股票基础信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票信息"
                ],
                "summary": "根据股票代码删除股票信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "股票代码",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stocks/{id}": {
            "get": {
                "description": "通过股票ID获取详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票信息"
                ],
                "summary": "根据ID获取股票信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "股票ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StockBasicInfo"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "根据ID更新股票基础信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票信息"
                ],
                "summary": "更新股票信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "股票ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "股票信息",
                        "name": "stock",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StockBasicInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StockBasicInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID删除股票记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股票信息"
                ],
                "summary": "删除股票信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "股票ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.StockBasicInfo": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "string",
                    "example": "上海"
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-08-13T10:00:00+08:00"
                },
                "full_name": {
                    "type": "string",
                    "example": "上海浦东发展银行股份有限公司"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "industry": {
                    "type": "string",
                    "example": "银行"
                },
                "is_hs": {
                    "type": "boolean",
                    "example": true
                },
                "listing_date": {
                    "type": "string",
                    "example": "1999-11-10"
                },
                "market": {
                    "type": "string",
                    "example": "主板"
                },
                "name": {
                    "type": "string",
                    "example": "浦发银行"
                },
                "outstanding_shares": {
                    "type": "number",
                    "example": 2930026
                },
                "status": {
                    "type": "string",
                    "example": "上市"
                },
                "symbol": {
                    "type": "string",
                    "example": "600000"
                },
                "total_shares": {
                    "type": "number",
                    "example": 2930026
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-08-13T10:00:00+08:00"
                }
            }
        },
        "models.StockDailyData": {
            "type": "object",
            "properties": {
                "adj_close": {
                    "description": "后复权收盘价",
                    "type": "number"
                },
                "amplitude": {
                    "description": "振幅(%)",
                    "type": "number"
                },
                "change_amount": {
                    "description": "涨跌额",
                    "type": "number"
                },
                "change_percent": {
                    "description": "涨跌幅(%)",
                    "type": "number"
                },
                "close": {
                    "description": "收盘价",
                    "type": "number"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "high": {
                    "description": "最高价",
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "low": {
                    "description": "最低价",
                    "type": "number"
                },
                "open": {
                    "description": "开盘价",
                    "type": "number"
                },
                "pb": {
                    "description": "市净率",
                    "type": "number"
                },
                "pe_ttm": {
                    "description": "市盈率(TTM)",
                    "type": "number"
                },
                "symbol": {
                    "description": "股票代码",
                    "type": "string"
                },
                "trade_date": {
                    "description": "交易日期",
                    "type": "string"
                },
                "turnover": {
                    "description": "成交额(元)",
                    "type": "number"
                },
                "turnover_rate": {
                    "description": "换手率(%)",
                    "type": "number"
                },
                "volume": {
                    "description": "成交量(股)",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.3.99:3003",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "股票信息 API",
	Description:      "股票基础信息管理 RESTful API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
